### ISSUE TITLE
Fix bug causing new Longs not to show in All Txs table

### ISSUE THREAD

**Issue by DannyDelott** [delvtech/hyperdrive-frontend#958]
Newly opened Long position is not showing up in the All Transactions table. We should check that we're requesting the right range of events

https://discord.com/channels/754739461707006013/1227673316114956309/1228792141271142561

**Comment by slundqui** [comment]
This issue seems to extend past just longs. For example, looking at etherscan for transactions on the 14 day eth pool shows that there were longs + shorts recently that's not showing up in the All Transactions table.
![image](https://github.com/delvtech/hyperdrive-frontend/assets/1431723/01fe31c2-2c29-4910-aad4-b6358654c6f7)
![image](https://github.com/delvtech/hyperdrive-frontend/assets/1431723/b76be29c-1467-4d4c-b041-6f0d8e1c5030)
